apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-converter-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-converter-service
  template:
    metadata:
      labels:
        app: image-converter-service
    spec:
      containers:
      - name: image-converter-service
        image: ${REGISTRY}/image-converter-service:latest
        ports:
        - containerPort: 4003
        env:
        - name: PORT
          value: "4003"
        - name: STORAGE_TYPE
          value: "cloud"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws-secret-key
        - name: S3_BUCKET
          value: "medical-images"
        - name: GCS_BUCKET
          value: "medical-images"
        volumeMounts:
        - name: storage-volume
          mountPath: /data/storage
        - name: gcp-credentials
          mountPath: /etc/gcp
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: storage-pvc
      - name: gcp-credentials
        secret:
          secretName: gcp-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: image-converter-service
spec:
  selector:
    app: image-converter-service
  ports:
  - port: 4003
    targetPort: 4003
  type: ClusterIP