apiVersion: apps/v1
kind: Deployment
metadata:
  name: translator-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: translator-service
  template:
    metadata:
      labels:
        app: translator-service
    spec:
      containers:
      - name: translator-service
        image: ${REGISTRY}/translator-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: PORT
          value: "4001"
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: translator-service
spec:
  selector:
    app: translator-service
  ports:
  - port: 4001
    targetPort: 4001
  type: ClusterIP