version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/medical-app
    depends_on:
      - mongodb
      - translator-service
      - dicom-processor-service
      - image-converter-service
      - distribution-service
      - notification-service
    networks:
      - app-network

  # Servicio de Traducción
  translator-service:
    build:
      context: ./services/translator
      dockerfile: Dockerfile
    environment:
      - PORT=4001
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/medical-app
    depends_on:
      - mongodb
    networks:
      - app-network

  # Procesador DICOM
  dicom-processor-service:
    build:
      context: ./services/dicom-processor
      dockerfile: Dockerfile
    environment:
      - PORT=4002
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/data/storage
    volumes:
      - storage-data:/data/storage
    networks:
      - app-network

  # Convertidor de Imágenes
  image-converter-service:
    build:
      context: ./services/image-converter
      dockerfile: Dockerfile
    environment:
      - PORT=4003
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/data/storage
    volumes:
      - storage-data:/data/storage
    networks:
      - app-network

  # Servicio de Distribución
  distribution-service:
    build:
      context: ./services/distribution
      dockerfile: Dockerfile
    environment:
      - PORT=4004
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/medical-app
    depends_on:
      - mongodb
    networks:
      - app-network

  # Servicio de Notificaciones
  notification-service:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    environment:
      - PORT=4005
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/medical-app
    depends_on:
      - mongodb
    networks:
      - app-network

  # Base de datos MongoDB
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
  storage-data: